import Link from 'next/link';
import {
  FolderOpenIcon,
  MagnifyingGlassIcon,
  SparklesIcon,
  DocumentTextIcon,
} from '@heroicons/react/24/outline';

export const metadata = {
  description: 'Intelligent document search and exploration powered by AI',
  openGraph: {
    type: 'website'
  }
};

const features = [
  {
    name: 'Document Explorer',
    description: 'Browse all your documents in a clean, organized file browser view with sorting and filtering.',
    icon: FolderOpenIcon,
    href: '/explorer',
  },
  {
    name: 'Semantic Search',
    description: 'Find documents using natural language queries powered by AI embeddings.',
    icon: MagnifyingGlassIcon,
    href: '/search',
  },
  {
    name: 'AI Summaries',
    description: 'Get intelligent summaries of your documents generated by LLama 3.1.',
    icon: SparklesIcon,
    href: '/explorer',
  },
  {
    name: 'Similar Documents',
    description: 'Discover related documents based on semantic similarity.',
    icon: DocumentTextIcon,
    href: '/explorer',
  },
];

export default function HomePage() {
  return (
    <div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8">
      {/* Hero Section */}
      <div className="text-center">
        <h1 className="text-4xl font-bold tracking-tight text-neutral-900 sm:text-5xl md:text-6xl dark:text-white">
          <span className="block">IntelliFile</span>
          <span className="block text-blue-600 dark:text-blue-400">
            AI-Powered Document Search
          </span>
        </h1>
        <p className="mx-auto mt-6 max-w-2xl text-lg text-neutral-600 dark:text-neutral-400">
          Explore, search, and understand your documents with intelligent AI features.
          Upload PDFs and DOCX files, then find information using natural language queries.
        </p>
        <div className="mt-10 flex items-center justify-center gap-4">
          <Link
            href="/explorer"
            className="rounded-lg bg-blue-600 px-6 py-3 text-base font-semibold text-white shadow-sm hover:bg-blue-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600"
          >
            Open Explorer
          </Link>
          <Link
            href="/search"
            className="rounded-lg border border-neutral-300 bg-white px-6 py-3 text-base font-semibold text-neutral-900 shadow-sm hover:bg-neutral-50 dark:border-neutral-700 dark:bg-neutral-800 dark:text-white dark:hover:bg-neutral-700"
          >
            Search Documents
          </Link>
        </div>
      </div>

      {/* Features Grid */}
      <div className="mt-24">
        <h2 className="text-center text-2xl font-bold text-neutral-900 dark:text-white">
          Features
        </h2>
        <div className="mt-12 grid gap-8 sm:grid-cols-2 lg:grid-cols-4">
          {features.map((feature) => (
            <Link
              key={feature.name}
              href={feature.href}
              className="group relative rounded-xl border border-neutral-200 bg-white p-6 shadow-sm transition-all hover:border-blue-300 hover:shadow-md dark:border-neutral-800 dark:bg-neutral-900 dark:hover:border-blue-700"
            >
              <div className="flex h-12 w-12 items-center justify-center rounded-lg bg-blue-100 text-blue-600 dark:bg-blue-900/30 dark:text-blue-400">
                <feature.icon className="h-6 w-6" />
              </div>
              <h3 className="mt-4 text-lg font-semibold text-neutral-900 group-hover:text-blue-600 dark:text-white dark:group-hover:text-blue-400">
                {feature.name}
              </h3>
              <p className="mt-2 text-sm text-neutral-600 dark:text-neutral-400">
                {feature.description}
              </p>
            </Link>
          ))}
        </div>
      </div>

      {/* Quick Stats / Getting Started */}
      <div className="mt-24 rounded-2xl bg-neutral-100 p-8 dark:bg-neutral-800/50">
        <h2 className="text-center text-2xl font-bold text-neutral-900 dark:text-white">
          Getting Started
        </h2>
        <div className="mt-8 grid gap-6 sm:grid-cols-3">
          <div className="text-center">
            <div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-blue-600 text-xl font-bold text-white">
              1
            </div>
            <h3 className="mt-4 font-semibold text-neutral-900 dark:text-white">
              Upload Documents
            </h3>
            <p className="mt-2 text-sm text-neutral-600 dark:text-neutral-400">
              Upload PDF or DOCX files through the API or drag-and-drop interface.
            </p>
          </div>
          <div className="text-center">
            <div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-blue-600 text-xl font-bold text-white">
              2
            </div>
            <h3 className="mt-4 font-semibold text-neutral-900 dark:text-white">
              Auto-Processing
            </h3>
            <p className="mt-2 text-sm text-neutral-600 dark:text-neutral-400">
              Documents are automatically processed, chunked, and embedded for search.
            </p>
          </div>
          <div className="text-center">
            <div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-blue-600 text-xl font-bold text-white">
              3
            </div>
            <h3 className="mt-4 font-semibold text-neutral-900 dark:text-white">
              Search & Explore
            </h3>
            <p className="mt-2 text-sm text-neutral-600 dark:text-neutral-400">
              Use natural language to find information across all your documents.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
