import Link from 'next/link';
import Image from 'next/image';
import {
  FolderOpenIcon,
  MagnifyingGlassIcon,
  SparklesIcon,
  DocumentTextIcon,
} from '@heroicons/react/24/outline';
import { ServerStatusBanner } from '@/components/layout/server-status-banner';

export const metadata = {
  description: 'Intelligent document search and exploration powered by AI',
  openGraph: {
    type: 'website'
  }
};

const features = [
  {
    name: 'Document Explorer',
    description: 'Browse all your documents in a clean, organized file browser view with sorting and filtering.',
    icon: FolderOpenIcon,
    href: '/explorer',
  },
  {
    name: 'Semantic Search',
    description: 'Find documents using natural language queries powered by AI embeddings.',
    icon: MagnifyingGlassIcon,
    href: '/search',
  },
  {
    name: 'AI Summaries',
    description: 'Get intelligent summaries of your documents generated by LLama 3.1.',
    icon: SparklesIcon,
    href: '/explorer',
  },
  {
    name: 'Similar Documents',
    description: 'Discover related documents based on semantic similarity.',
    icon: DocumentTextIcon,
    href: '/explorer',
  },
];

export default function HomePage() {
  return (
    <>
      {/* Server Status Banner */}
      <ServerStatusBanner />

      <div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8">
        {/* Hero Section */}
        <div className="text-center">
          <h1 className="text-4xl font-bold tracking-tight text-neutral-900 sm:text-5xl md:text-6xl dark:text-white">
            <span className="block">IntelliFile</span>
            <span className="block text-blue-600 dark:text-blue-400">
              AI-Powered Document Search
            </span>
          </h1>
          <p className="mx-auto mt-6 max-w-2xl text-lg text-neutral-600 dark:text-neutral-400">
            Explore, search, and understand your documents with intelligent AI features.
            Upload PDFs and DOCX files, then find information using natural language queries.
          </p>
          <div className="mt-10 flex items-center justify-center gap-4">
            <Link
              href="/explorer"
              className="rounded-lg bg-blue-600 px-6 py-3 text-base font-semibold text-white shadow-sm hover:bg-blue-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600"
            >
              Open Explorer
            </Link>
            <Link
              href="/search"
              className="rounded-lg border border-neutral-300 bg-white px-6 py-3 text-base font-semibold text-neutral-900 shadow-sm hover:bg-neutral-50 dark:border-neutral-700 dark:bg-neutral-800 dark:text-white dark:hover:bg-neutral-700"
            >
              Search Documents
            </Link>
            <Link
              href="https://github.com/aa-del9/rag-file-explorer"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 rounded-lg border border-neutral-300 bg-white px-6 py-3 text-base font-semibold text-neutral-900 shadow-sm hover:bg-neutral-50 dark:border-neutral-700 dark:bg-neutral-800 dark:text-white dark:hover:bg-neutral-700"
            >
              <svg className="h-5 w-5" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                <path fillRule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" clipRule="evenodd" />
              </svg>
              GitHub
            </Link>
          </div>
        </div>

        {/* Features Grid */}
        <div className="mt-24">
          <h2 className="text-center text-2xl font-bold text-neutral-900 dark:text-white">
            Features
          </h2>
          <div className="mt-12 grid gap-8 sm:grid-cols-2 lg:grid-cols-4">
            {features.map((feature) => (
              <Link
                key={feature.name}
                href={feature.href}
                className="group relative rounded-xl border border-neutral-200 bg-white p-6 shadow-sm transition-all hover:border-blue-300 hover:shadow-md dark:border-neutral-800 dark:bg-neutral-900 dark:hover:border-blue-700"
              >
                <div className="flex h-12 w-12 items-center justify-center rounded-lg bg-blue-100 text-blue-600 dark:bg-blue-900/30 dark:text-blue-400">
                  <feature.icon className="h-6 w-6" />
                </div>
                <h3 className="mt-4 text-lg font-semibold text-neutral-900 group-hover:text-blue-600 dark:text-white dark:group-hover:text-blue-400">
                  {feature.name}
                </h3>
                <p className="mt-2 text-sm text-neutral-600 dark:text-neutral-400">
                  {feature.description}
                </p>
              </Link>
            ))}
          </div>
        </div>

        {/* Quick Stats / Getting Started */}
        <div className="mt-24 rounded-2xl bg-neutral-100 p-8 dark:bg-neutral-800/50">
          <h2 className="text-center text-2xl font-bold text-neutral-900 dark:text-white">
            Getting Started
          </h2>
          <div className="mt-8 grid gap-6 sm:grid-cols-3">
            <div className="text-center">
              <div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-blue-600 text-xl font-bold text-white">
                1
              </div>
              <h3 className="mt-4 font-semibold text-neutral-900 dark:text-white">
                Upload Documents
              </h3>
              <p className="mt-2 text-sm text-neutral-600 dark:text-neutral-400">
                Upload PDF or DOCX files through the API or drag-and-drop interface.
              </p>
            </div>
            <div className="text-center">
              <div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-blue-600 text-xl font-bold text-white">
                2
              </div>
              <h3 className="mt-4 font-semibold text-neutral-900 dark:text-white">
                Auto-Processing
              </h3>
              <p className="mt-2 text-sm text-neutral-600 dark:text-neutral-400">
                Documents are automatically processed, chunked, and embedded for search.
              </p>
            </div>
            <div className="text-center">
              <div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-blue-600 text-xl font-bold text-white">
                3
              </div>
              <h3 className="mt-4 font-semibold text-neutral-900 dark:text-white">
                Search & Explore
              </h3>
              <p className="mt-2 text-sm text-neutral-600 dark:text-neutral-400">
                Use natural language to find information across all your documents.
              </p>
            </div>
          </div>
        </div>

        {/* Architecture Diagram Section */}
        <div className="mt-24">
          <h2 className="text-center text-2xl font-bold text-neutral-900 dark:text-white">
            System Architecture
          </h2>
          <p className="mx-auto mt-4 max-w-2xl text-center text-neutral-600 dark:text-neutral-400">
            IntelliFile is built with a modern, modular architecture for intelligent document processing.
          </p>
          <div className="mt-8 flex justify-center">
            <div className="w-full max-w-4xl overflow-hidden rounded-xl border border-neutral-200 bg-white p-4 shadow-sm dark:border-neutral-800 dark:bg-neutral-900">
              <Image
                src="/images/system-architecture.png"
                alt="IntelliFile System Architecture - Next.js Frontend, FastAPI Backend, ChromaDB Vector Store, Ollama LLM"
                width={1200}
                height={675}
                className="w-full rounded-lg"
                loading="lazy"
                placeholder="blur"
                blurDataURL="/images/image.png"
              />
            </div>
          </div>
        </div>

        {/* Data Flow Diagram Section */}
        <div className="mt-24">
          <h2 className="text-center text-2xl font-bold text-neutral-900 dark:text-white">
            Data Flow
          </h2>
          <p className="mx-auto mt-4 max-w-2xl text-center text-neutral-600 dark:text-neutral-400">
            See how documents flow through the RAG pipeline from upload to intelligent search.
          </p>
          <div className="mt-8 flex justify-center">
            <div className="w-full max-w-4xl overflow-hidden rounded-xl border border-neutral-200 bg-white p-4 shadow-sm dark:border-neutral-800 dark:bg-neutral-900">
              <Image
                src="/images/data-flow-diagram.png"
                alt="IntelliFile Data Flow - Upload, Process, Embed, Store, Search, LLM Response"
                width={1200}
                height={675}
                className="w-full rounded-lg"
                loading="lazy"
                placeholder="blur"
                blurDataURL="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNYvXr1fwAG/gL+Ig4R7wAAAABJRU5ErkJggg=="
              />
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
